# TWFaith Config File
# Version : Snapshot 1

# Pray cool down
pray-cool-down: 10

# Base stamina regeneration per second
base-stamina-regen: 10

# Powers
# cost: The number of faith points to purchase the upgrade
# stamina: The stamina cost (either per second or per trigger) to use the power
# cooldown: How many seconds the god must wait before triggering the power again. Only for triggered powers.

# Divine Intervention
divine-cost: 5
divine-stamina: 11
divine-cooldown: 10

# Hell's Fury
hells-cost: 5
hells-stamina: 11

# Mana
mana-cost: 5
mana-stamina: 11
mana-cooldown: 10

# Powerful Flock
flock-cost: 5
flock-stamina: 11

# Summon God
summon-cost: 5
summon-stamina: 11
summon-cooldown: 10

# Terrain Bonus
terrain-cost: 5
terrain-stamina: 11

# Lion's Heart
lions-heart-cost: 5
lions-heart-stamina: 11

# Savior
savior-cost: 5
savior-stamina: 11
savior-cooldown: 10

# Taunt
taunt-cost: 5
taunt-stamina: 11
taunt-cooldown: 10

# Insidious
insidious-cost: 5
insidious-stamina: 11

# Explosive Landing
explosive-cost: 5
explosive-stamina: 11
explosive-cooldown: 10

# Flood
flood-cost: 5
flood-stamina: 11
flood-cooldown: 10

# Crumbling
crumbling-cost: 5
crumbling-stamina: 11

# Discombobulation
discombobulation-cost: 5
discombobulation-stamina: 11
discombobulation-cooldown: 10

# Entangle
entangle-cost: 5
entangle-stamina: 11
entangle-cooldown: 10

# Heavy Boots
heavy-cost: 5
heavy-stamina: 11

# Intoxicate
intoxicate-cost: 5
intoxicate-stamina: 11